/*
 * aes_stub.c — AES-128-CTR runtime decryption stub (shared by strenc + vmpass).
 *
 * Public entry points:
 *   __aes_decrypt()       — used by strenc (reconstructs key from providers)
 *   __obf_aes_ctr_decrypt()  — used by vmpass (caller supplies expanded key)
 *
 * Both passes link this same bitcode; the linker-level dedup check in
 * This file is compiled to LLVM bitcode during the LLVM build and embedded
 * as a byte array inside StringEncryption.cpp.  At pass runtime, the bitcode
 * is parsed, patched with the key-provider bodies generated by the pass, and
 * linked into the target module so that all subsequent obfuscation passes
 * (flattening, MBA, BCF, adec …) also cover the decryption stub.
 *
 * ── Key interface ──────────────────────────────────────────────────────────
 *
 *  The pass generates two "key provider" IR functions whose bodies contain
 *  the compile-time AES round-key material:
 *
 *    void __aes_key_a(uint8_t out[88])   ← memcpy from .strenc.kd global
 *    void __aes_key_b(uint8_t out[88])   ← 88 individual store immediates
 *                                              in .strenc.kt code section
 *
 *  Both are declared extern here; their definitions are injected by the pass
 *  after linking this stub module into the target module.
 *
 * ── Call site interface ────────────────────────────────────────────────────
 *
 *    void __aes_decrypt(uint8_t *buf, uint32_t len, const uint8_t *nonce8)
 *
 *  buf    : stack buffer pre-filled with the ciphertext (modified in-place).
 *  len    : plaintext length (does NOT include the null terminator byte).
 *  nonce8 : 8-byte per-string nonce (unique per string index + content hash).
 *
 * ── Segments ──────────────────────────────────────────────────────────────
 *
 *  __aes_decrypt and helpers → default .text / __TEXT,__text
 *  __aes_key_a               → generated by pass, memcpy from .strenc.kd
 *  __aes_key_b               → generated by pass, stores in .strenc.kt
 *
 * ── Compile flags used by CMakeLists ──────────────────────────────────────
 *
 *   clang -O2 -emit-llvm -c -ffreestanding -fno-builtin-memcpy
 *         -fno-builtin-memset -fvisibility=hidden
 *
 * IMPORTANT: No string literals anywhere in this file — the strenc pass
 * itself would try to re-encrypt them, causing double-encryption bugs.
 */

#include <stdint.h>

/* ── key providers declared extern, bodies injected by pass ──────────────── */
extern void __aes_key_a(uint8_t out[88]);
extern void __aes_key_b(uint8_t out[88]);

/* ── portable minimal memcpy / memset (avoid builtin; -ffreestanding) ────── */
static void se_memcpy(void *dst, const void *src, uint32_t n) {
    uint8_t       *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    for (uint32_t i = 0; i < n; i++) d[i] = s[i];
}
static void se_memset(void *dst, uint8_t v, uint32_t n) {
    uint8_t *d = (uint8_t *)dst;
    for (uint32_t i = 0; i < n; i++) d[i] = v;
}

/* ── AES-128 lookup tables ───────────────────────────────────────────────── */

/* Standard AES forward S-box */
static const uint8_t SE_SBOX[256] = {
    0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
    0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
    0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
    0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
    0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
    0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
    0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
    0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
    0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
    0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
    0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
    0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
    0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
    0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
    0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
    0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16
};

/* ── AES GF(2^8) multiply by 2 (xtime) ──────────────────────────────────── */
static inline uint8_t xtime(uint8_t x) {
    return (uint8_t)((x << 1) ^ ((x >> 7) * 0x1bu));
}

/* ── AES ShiftRows (in-place, column-major layout) ───────────────────────── */
/*
 * AES state layout: s[col*4 + row]
 *   col 0  col 1  col 2  col 3
 *   s[0]   s[4]   s[8]   s[12]    row 0 — no shift
 *   s[1]   s[5]   s[9]   s[13]    row 1 — left-shift 1
 *   s[2]   s[6]   s[10]  s[14]    row 2 — left-shift 2
 *   s[3]   s[7]   s[11]  s[15]    row 3 — left-shift 3
 */
static void aes_shift_rows(uint8_t s[16]) {
    uint8_t t;
    /* row 1: rotate left by 1 */
    t = s[1]; s[1] = s[5]; s[5] = s[9]; s[9] = s[13]; s[13] = t;
    /* row 2: rotate left by 2 */
    t = s[2]; s[2] = s[10]; s[10] = t;
    t = s[6]; s[6] = s[14]; s[14] = t;
    /* row 3: rotate left by 3  (= right by 1) */
    t = s[15]; s[15] = s[11]; s[11] = s[7]; s[7] = s[3]; s[3] = t;
}

/* ── AES MixColumns (in-place) ───────────────────────────────────────────── */
static void aes_mix_columns(uint8_t s[16]) {
    for (int c = 0; c < 4; c++) {
        uint8_t a = s[c*4+0], b = s[c*4+1], cc = s[c*4+2], d = s[c*4+3];
        uint8_t tmp = a ^ b ^ cc ^ d;
        s[c*4+0] ^= tmp ^ xtime((uint8_t)(a ^ b));
        s[c*4+1] ^= tmp ^ xtime((uint8_t)(b ^ cc));
        s[c*4+2] ^= tmp ^ xtime((uint8_t)(cc ^ d));
        s[c*4+3] ^= tmp ^ xtime((uint8_t)(d ^ a));
    }
}

/* ── AES-128 encrypt one 16-byte block ───────────────────────────────────── */
/*
 * rk   : 176-byte expanded key schedule (11 round keys × 16 bytes)
 * block: 16-byte block encrypted in-place
 *
 * NOTE: This is NOT static — __obf_aes_ctr_decrypt needs it, and keeping it
 * as a single definition avoids code duplication when LTO merges strenc + vmpass.
 */
static void aes128_encrypt_block(const uint8_t rk[176], uint8_t block[16]) {
    uint8_t s[16];
    se_memcpy(s, block, 16);

    /* AddRoundKey — round 0 */
    for (int i = 0; i < 16; i++) s[i] ^= rk[i];

    /* Rounds 1–9: SubBytes, ShiftRows, MixColumns, AddRoundKey */
    for (int r = 1; r <= 9; r++) {
        for (int i = 0; i < 16; i++) s[i] = SE_SBOX[s[i]];
        aes_shift_rows(s);
        aes_mix_columns(s);
        for (int i = 0; i < 16; i++) s[i] ^= rk[r*16 + i];
    }

    /* Round 10: SubBytes, ShiftRows, AddRoundKey (no MixColumns) */
    for (int i = 0; i < 16; i++) s[i] = SE_SBOX[s[i]];
    aes_shift_rows(s);
    for (int i = 0; i < 16; i++) s[i] ^= rk[160 + i];

    se_memcpy(block, s, 16);
}

/* ── CTR counter increment ─ */
static inline void ctr_inc(uint8_t ctr[16]) {
    for (int i = 15; i >= 8; i--) { if (++ctr[i]) break; }
}


/*
* __obf_aes_ctr_decrypt  —  Shared AES-CTR decryption with caller-provided key.
*
* This is the common decryption primitive used by both strenc (indirectly via
* __strenc_decrypt) and vmpass (directly from the .init_array constructor).
*
* buf       : buffer to decrypt in-place.
* len       : number of bytes to process.
* rk176     : pointer to the full 176-byte expanded AES-128 round-key schedule.
* nonce8    : 8-byte nonce; counter block = nonce8 || 0x00{8}.
*
* When strenc and vmpass are both active, this function exists exactly once in
* the binary — the linker-level check in linkStub() deduplicates the bitcode.
* ═══════════════════════════════════════════════════════════════════════════ */
__attribute__((noinline))
void __obf_aes_ctr_decrypt(uint8_t *buf, uint32_t len,
                            const uint8_t *rk176, const uint8_t *nonce8) {
    uint8_t ctr[16];
    se_memcpy(ctr, nonce8, 8);
    se_memset(ctr + 8, 0, 8);

    uint32_t offset = 0;
    while (offset < len) {
        uint8_t ks[16];
        se_memcpy(ks, ctr, 16);
        aes128_encrypt_block(rk176, ks);

        uint32_t n = (len - offset < 16u) ? (len - offset) : 16u;
        for (uint32_t i = 0; i < n; i++)
            buf[offset + i] ^= ks[i];

        offset += 16u;
        ctr_inc(ctr);
    }
}


/* ═══════════════════════════════════════════════════════════════════════════
 * __strenc_decrypt
 *
 * Primary entry point injected at each string use-site by the pass.
 *
 * buf    : stack buffer, pre-filled with ciphertext, decrypted in-place.
 * len    : plaintext byte count (does NOT include the null terminator).
 * nonce8 : 8-byte nonce — unique per string (FNV-64 of index + content).
 *
 * Counter block layout:  | nonce8 (8 bytes) | counter64_be (8 bytes, = 0) |
 * Counter increments in big-endian in the upper 8 bytes after each block.
 * ═══════════════════════════════════════════════════════════════════════════ */
__attribute__((noinline))
void __aes_decrypt(uint8_t *buf, uint32_t len, const uint8_t *nonce8) {
    /* ── 1. Recombine key halves → 176-byte round-key schedule ── */
    uint8_t ha[88], hb[88], rk[176];
    __aes_key_a(ha);          /* first 88 bytes  — from data segment  */
    __aes_key_b(hb);          /* second 88 bytes — from code segment  */
    se_memcpy(rk,      ha, 88);
    se_memcpy(rk + 88, hb, 88);

    /* —— 2. Delegate to the shared CTR routine —— */
    __obf_aes_ctr_decrypt(buf, len, rk, nonce8);
}