"""HTML report generation and aggregation index."""

from __future__ import annotations

import html
import sys
from pathlib import Path
from typing import Optional

from ..util import run_cmd


def find_obf_report_html_tool(build_dir: Path) -> Optional[Path]:
    """Best-effort locator for llvm/utils/obf_report_html.py."""
    here = Path(__file__).resolve().parents[2]
    candidates: list[Path] = [
        here / "obf_report_html.py",
        here / "llvm" / "utils" / "obf_report_html.py",
    ]

    b = build_dir.resolve()
    for p in [b] + list(b.parents):
        candidates.append(p / "llvm" / "utils" / "obf_report_html.py")
        candidates.append(p / "llvm-project" / "llvm" / "utils" / "obf_report_html.py")

    for c in candidates:
        if c.exists():
            return c
    return None


def gen_obf_report_html(
    tool: Path, report_json: Path, out_html: Path, report_dir: Path, *,
    verbose: bool,
) -> Optional[str]:
    """Return error string on failure, else None."""
    try:
        run_cmd(
            [
                sys.executable,
                str(tool),
                "--json", str(report_json),
                "--out", str(out_html),
                "--report-dir", str(report_dir),
            ],
            verbose=verbose,
            capture=True,
        )
        return None
    except Exception as e:
        return str(e)


def write_obf_reports_index(report_root: Path, results: list) -> Path:
    """Write a simple index.html linking to all per-test reports."""
    rows = []
    for r in results:
        status = r.status
        st_cls = "pass" if status == "PASS" else "fail" if status == "FAIL" else "skip"

        links = []
        for label, rel in sorted(r.report_html.items(), key=lambda kv: kv[0]):
            href = html.escape(rel, quote=True)
            links.append(f'<a href="{href}">{html.escape(label)}</a>')
        links_html = " ".join(links) if links else "&mdash;"

        rows.append(
            "<tr>"
            f"<td class='test'>{html.escape(r.name)}</td>"
            f"<td class='cat'>{html.escape(r.category)}</td>"
            f"<td class='st {st_cls}'>{html.escape(status)}</td>"
            f"<td class='t'>{r.elapsed:.2f}s</td>"
            f"<td class='links'>{links_html}</td>"
            "</tr>"
        )

    doc = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>LLVM Obfuscator — Test Reports</title>
  <style>
    body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,Noto Sans,sans-serif;margin:24px;}
    h1{font-size:20px;margin:0 0 12px 0;}
    .meta{color:#555;margin-bottom:16px;}
    table{border-collapse:collapse;width:100%;}
    th,td{border:1px solid #ddd;padding:8px;vertical-align:top;}
    th{background:#f6f6f6;text-align:left;}
    td.st.pass{background:#e7f7ee;}
    td.st.fail{background:#ffe8e8;}
    td.st.skip{background:#fff6db;}
    td.links a{margin-right:10px;white-space:nowrap;}
    .small{font-size:12px;color:#666;}
  </style>
</head>
<body>
  <h1>LLVM Obfuscator — Runtime Test Reports</h1>
  <div class="meta small">Generated by obf_runtime_tests.py</div>
  <table>
    <thead>
      <tr>
        <th>Test</th><th>Category</th><th>Status</th><th>Time</th><th>Reports</th>
      </tr>
    </thead>
    <tbody>
""" + "\n".join(rows) + """
    </tbody>
  </table>
</body>
</html>
"""

    out = report_root / "index.html"
    out.write_text(doc, encoding="utf-8", newline="\n")
    return out
